apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app3_devseccon
  annotations:
    github.com/project-slug: Frentzen/app3_devseccon
spec:
  type: other
  lifecycle: unknown
  owner: guests
